### ISSUE TITLE
dplyr verb approach: A blueprint for tidytuesdayR

### ISSUE THREAD

**Issue by chuckleong21** [thebioengineer/tidytuesdayR#29]
Very excited to get to know this package! I have a few ideas about improving its functionality upon the completion of my very own `tidy_tuesday()` (doing what this package does):

**`tt_open()`**: initiate a **`tt`** object given week or date specifications.

Once a `tt` object has been initialized, users may apply the following actions:

**`tt_browse()`**: browse the specified git repo webpage.

**`tt_view()`**: does what `tt_available()` do but only given a `tt` object.

**`tt_scan()`**: scan the repo to see what files are available.

**`tt_load()`**: does what `tt_load()` do as before but now with a restriction of object class.

**`tt_archive()`**: 'clone' the repo locally from git by downloading all the files.

Other (farfetched) thoughts:

**`tt_contribute()`**: allows users to post their work using twitter API(?).

**`tt_submit()`**: allows users to submit a dataset via filing an issue on Github(?).

Should these verbs work in chain of commands? For instance, one must:
tt_open() %>% tt_scan() %>% tt_load() to complete a workflow of getting data, or tt_open() %>% tt_view() to look at the dataset list in viewer. I do concern a tighter pipe flow creates unnecessary object classes.

Thoughts?

**Comment by thebioengineer** [comment]
Thanks for the ideas @chuckleong21 ! I am formulating some thoughts, and will drop them here as I complete of them.

## Current State
My goal of {tidytuesdayR} is to lower the barrier for accessing the data made available by @jthomasmock and the team over at R4DS. 

First it has been making the user-side workhorse of a function function we have right now - `tt_load()`. Making it so It Just Works<sup>tm</sup> with dates and years/weeks has been a lift, but also making it so it can download literally any file that thomas has made available so far. 

I'm not so sure a `tt_open()` type function, which as I read it essentially opens a "connection" to the weeks data is not necessary - we kind of have that in the `tt_load_gh()` function, which downloads the list of the files available and the readme. An option would be to change the name to be more descriptive to the user and update tt_load so also ust Works<sup>tm</sup> if the input is  a `tt` object.

I think a number of the functions you suggested exist in some form or another, but are not documented well enough since you couldn't find them offhand. 

## For the Future
### Functionality
It has long been in my mental roadmap for the project to eventually be able to tweet directly from the R session, and I would appreciate thoughts on how to best implement that. I had not thought of a tt_submit type function. That would be pretty cool.

### Documentation
I have thought that the package was fairly self-documenting, but maybe a bookdown or pkgdown site that is better fleshed out - (and more through R4DS? @jonthegeek @jthomasmock?) would be beneficial.

**Comment by chuckleong21** [comment]
It is true `tt_load()` does most of the work for the goal of this package. However, the setup of `tt_open()` takes a page out of the book of `parsnip` and `recipes` - a blueprint.

Instead of retriving all objects using GET method at once from `tt_load()`. The process could be broken down into pieces:
- `tt_open()`s a `<tt session>`:

  ```r
  print(tt_open(x = 2019, week = 45))

  #> <tt session>
  #>    TidyTuesday Week 45, 2019 (2019-11-05)
  #>    Modes Less Traveled - Bicycling and Walking to Work in the
  #>    United States: 2008-2012
  #>
  #>    13 files available:
  #>    acs-25.pdf               
  #>    bike_walk.R              
  #>    commute.csv             
  #>    pic1.png                 
  #>    pic2.png                 
  #>    readme.md               
  #>    supplemental-table1.xlsx 
  #>    supplemental-table2.xlsx 
  #>    supplemental-table3.xlsx
  #>    supplemental-table4.xlsx 
  #>    supplemental-table5.xlsx 
  #>    supplemental-table6.xlsx
  #>    table_3.csv 

  #> -- opens README.md in viewer --
  ```
- `tt_load()` then reads data / downloads file given methods for different file types. This gives users some freedom to select what data they want to load into the R environment. Currently `tt_load()` only deals with data mentioned in **README.md** and print out `Available Datasets:` may be misleading.

`tt_load()` does not seem to handle rds files. For example, R session hangs running `tt_load(x = 2019, week = 1)`

Most of the time, csv and markdown files present in the weekly folder. I did a little scraping on the file types listed for each week just in 2019 alone: 
```r
#    ext  n percent
# 1  csv 98   58.3%
# 2   md 46   27.4%
# 3    R  8    4.8%
# 4 xlsx  6    3.6%
# 5  png  4    2.4%
# 6  rds  3    1.8%
# 7 docx  1    0.6%
# 8  pdf  1    0.6%
# 9  rmd  1    0.6%
```
There is also the `tt_load_gh()` glitch. `.readme` attribute prints walls of HTML that aren't terribly helpful. Changing it to `TRUE`/`FALSE` for the availability of README.md would be better.

To implement a tweeting session from R directly, the first idea I have is to build a package add-in that pops up a Shiny widget. The problem is whether we could make it send a POST request from the localhost to twitter.com. 
(p.s. I have not written an add-in before.)

A `pkgdown` website sounds nice, but maybe it's not necessary? The goal of {tidytuesdayR} is less technical and package usage is fairly lucid.

**Comment by thebioengineer** [comment]
The most recent version of the package (0.2.1) should be able to handle rds and rda files. I had just added that feature earlier this week. 
``` r
# remotes::install_github("thebioengineer/tidytuesdayR")
library(tidytuesdayR)
tt<-tt_load(x = 2019, week = 1)
head(tt$rstats_tweets)
#> # A tibble: 6 x 88
#>   user_id status_id created_at          screen_name text  source
#>   <chr>   <chr>     <dttm>              <chr>       <chr> <chr> 
#> 1 5685812 10754715~ 2018-12-19 19:22:47 hrbrmstr    JSON~ Buffer
#> 2 5685812 99492470~ 2018-05-11 12:58:28 hrbrmstr    #rst~ Twitt~
#> 3 5685812 99908311~ 2018-05-23 00:22:31 hrbrmstr    Whoa~ Twitt~
#> 4 5685812 10644994~ 2018-11-19 12:43:29 hrbrmstr    Supe~ Buffer
#> 5 5685812 10037671~ 2018-06-04 22:35:21 hrbrmstr    macO~ Twitt~
#> 6 5685812 10018088~ 2018-05-30 12:53:31 hrbrmstr    Work~ Twitt~
#> # ... with 82 more variables: display_text_width <dbl>,
# ... (I cut off the additional print out)
```

<sup>Created on 2019-11-10 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

You are correct in that that the `tt` object needs a print method so it doesn't print out that wall of html text as you saw and behaves more similarly to the printing of the `tt_data` object. That has been on the "to do" list. I'll open a branch and take care of that tonight.

There is a function called `tt_read_data()` that accepts a `tt` object generated by `tt_load_gh()`, and the name of the file you want to download. This does that I think you are looking for:
```r 
library(tidyverse)
library(tidytuesdayR)

# Roughly equivalent to your `tt_open` suggestion
economist_tt <- tt_load_gh(2019, week = 16)

# To view the readme in the viewer
readme(economist_tt)

# Download the file
economist_data <- economist_tt %>% 
  tt_read_data("brexit.csv")
```

Right now I am thinking `tt_load_gh()` is not an obvious name for the function, Maybe `tt_summary()`?

**Comment by chuckleong21** [comment]
Finally, I have some time to again look at this issue.
`tt_summary()` sounds good and more explicit than assigning a tt method to `summary()`. Do give a thought to my blueprint proposal to print out tt_summary().

By the way, does `tt_load()` works swiftly for you? It always takes a (sometimes two) while to successfully load in the data. I don't think `readr::read_csv()` is causing the problem here after I tried the old-fashion way like we used to.

**Comment by thebioengineer** [comment]
Hey @chuckleong21, It is my turn to say finally I have some time to look at this issue 😆

If you want to take a look at making that print method for the `tt` object and submit a pull request I can review it and we can start a conversation around that.

As for `tt_load()` taking a moment, it is because it has a number of https requests to generate the object. First it validates the date/week you submit, then it extracts the list of files and readme, then it goes and downloads all the files to make available for `read_csv()`, etc. 

Looking at the profvis output of tt_load on the most recent dataset, it looks like most of the time is downloading the file from github. Comparing this to the most recent read_csv, my method was actually faster!

``` r
library(tidytuesdayR)

tt_start <- Sys.time()
tt <- tt_load("2019-12-03")
tt_end <- Sys.time()

read_start <- Sys.time()
tickets <- readr::read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-12-03/tickets.csv")
#> Parsed with column specification:
#> cols(
#>   violation_desc = col_character(),
#>   issue_datetime = col_datetime(format = ""),
#>   fine = col_double(),
#>   issuing_agency = col_character(),
#>   lat = col_double(),
#>   lon = col_double(),
#>   zip_code = col_double()
#> )
read_end <- Sys.time()


difftime(tt_end,tt_start)
#> Time difference of 9.091398 secs
difftime(read_end,read_start)
#> Time difference of 28.31201 secs
```

<sup>Created on 2019-12-07 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>
