### ISSUE TITLE
JSON in progress

### ISSUE THREAD

**Issue by jthomasmock** [thebioengineer/tidytuesdayR#47]
Creating a JSON master file for:
- Nested by year
  - Nested by week 
    - Named vector or 1x3 data.frame
      - File name
      - File + extension
      - delim

Will go into "Static" folder

**Comment by jthomasmock** [comment]
So I realized there's not MUCH of a reason to make this json.

I was able to output pretty quickly the files to a .csv or JSON file - there's some more manual stuff I'll need to do to parse the readme files that you were doing before.

Moving forward I can just add these weekly, but for the initial release I'll have to do much more spotchecking.

[CSV](https://github.com/rfordatascience/tidytuesday/blob/master/static/tt_data_type.csv)

If that format looks good I'll go through and filter it down to just the read-in data sets (not raw).

**Comment by thebioengineer** [comment]
Awesome! Thanks. The reason I was thinking JSON was that it is not limited to rectangular format that a CSV would enforce, and so that I could set it up to quickly work down the tree year -> date -> file -> file details. But it seems like we would want the same information for everything, so a csv might be better! Reading a csv is faster than a JSON, and easier to track through github by appending a new row. 

I will play around with it it a bit, but I think I would only need the result of this:
```r

library(tidyverse)

raw_csv <- readr::read_csv("https://github.com/rfordatascience/tidytuesday/blob/master/static/tt_data_type.csv?raw=true")
prepped_csv <- raw_csv %>% 
  mutate(
    clean_path = gsub("~/tidytuesday_github/","",year_path),
    data_path = file.path(clean_path, week_date, data_files)
  ) %>% 
  select(year, week_date, data_files, data_path, data_type, delim)

```

**Comment by thebioengineer** [comment]
Hey @jthomasmock, I'm realizing your definition for "week" would also be hugely helpful. (partly due to the week1 of 2020 being in 2019

**Comment by thebioengineer** [comment]
@jthomasmock - made lots of updates to attempt to simplify the api. One thing is that if we use the actual github API (api.github.com), we need to use exact names, including capitalization.

A few of the readme's are not consistent with capitalization. Can we be consistent with either `README.md` or `readme.md`?

**Comment by thebioengineer** [comment]
with the current merge to master (#51), this should be addressed and I will close this out.
