### ISSUE TITLE
Make tt_download a valid user command

### ISSUE THREAD

**Issue by francisbarton** [thebioengineer/tidytuesdayR#69]
Rather than have the week's data downloaded and directly converted into an object by `tt_load()`, I'd like the option to simply download all the files for the latest week to my current working directory, so that I can import them myself and have the actual files there for future reference.

(I don't want to clone the TT repository)

`tt_load` obviously does download the files, in order to import them, but they're not visible - as files - in the local directory after the import has completed.

If I try to run `tt_download` directly, I get an error:
```
> tidytuesdayR::tt_download(last_tuesday())
--- Starting Download ---

Error in if (dirpath == ".") { : argument is of length zero
In addition: Warning message:
tz(): Don't know how to compute timezone for object of class NULL; returning "UTC". This warning will become an error in the next major version of lubridate. 
```

Ideally I want to do something like:
```
library(tidytuesdayR)
library(here)

latest <- tidytuesdayR::last_tuesday()

if(!dir.exists(here(latest))) dir.create(here(latest))

tidytuesdayR::tt_download(last_tuesday(), files = "all", download_dir = here(latest))
```

**Comment by thebioengineer** [comment]
Hey @francisbarton - Ah, thanks for pointing out my documentation for that function is incorrect! It expects to get a `tt` object, which is output from the `tt_load_gh` function. 

Technically we do not "download" the files, in the "they are copied from the internet and saved in a temp dir" sense. I query the github API and are given a `raw` vector representation of the files that are then parsed by their respective tools into the object that you eventually see. nothing is written into a directory, all of this is handled in memory. The goal here is so that you always are using the most recent version of the data!

However, I can see your point of wanting to have copies saved locally, and I will see what I can do to make that happen. Otherwise you might have to work with saving the files manually from the `tt_data` object.

**Comment by francisbarton** [comment]
Very interesting @thebioengineer , thanks. Didn't realise it was a github API query, that makes sense. I can certainly cope with just using `tt_load()` or downloading/reading the data using the direct URLs given in the readme each week.
Feel free to close.
