### ISSUE TITLE
Parsing error when loading data with tt_load()?

### ISSUE THREAD

**Issue by Sdbock** [thebioengineer/tidytuesdayR#88]
When attempting to load the data from Feb 1 (within the Rmarkdown Tidy Tuesday Template), it starts to download the files, but then stops and gives a parsing error. Is there an issue with one of the file names?

`tt <- tt_load("2022-02-01")`

--- Compiling #TidyTuesday Information for 2022-02-01 ----
--- There are 3 files available ---
--- Starting Download ---

	Downloading file 1 of 3: `breed_traits.csv`
	Downloading file 2 of 3: `trait_description.csv`
	Downloading file 3 of 3: `breed_rank_all.csv`
 Error in parse_url(url) : length(url) == 1 is not TRUE

**Comment by thebioengineer** [comment]
Thanks for bringing this to my attention. I'll investigate and see what is going on!

**Comment by rocarvaj** [comment]
Hello! Any news on this issue?
I just installed tidytuesdayR and tried to load this week's data with:

```r
tt_data <- tidytuesdayR::tt_load(2022, week = 19)
```
And I'm getting the same error:

```
--- Compiling #TidyTuesday Information for 2022-05-10 ----
--- There are 2 files available ---
--- Starting Download ---

	Downloading file 1 of 2: `nyt_titles.tsv`
	Downloading file 2 of 2: `nyt_full.csv`

Error in parse_url(url) : length(url) == 1 is not TRUE
```

Thanks!

**Comment by thebioengineer** [comment]
Hey, sorry, this is because there was a transcription error in the tidytuesday repository. As you can see, it said it was trying to download `nyt_full.csv`, which does not exist, but `nyt_full.tsv` does. This is based on [tt_data_type.csv](https://github.com/rfordatascience/tidytuesday/edit/master/static/tt_data_type.csv), which is in the tidytuesday repo. I've submitted a bug fix

**Comment by rocarvaj** [comment]
Thanks!
Shame on me for not investigating a little where was the error coming from.
